### ISSUE TITLE
Replace GPU annotation by affinity in ML examples

### ISSUE THREAD

**Issue by goock** [coreweave/kubernetes-cloud#27]
Current, old-style annotation:

```
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: gpt-pvc
  annotations:
    serving.kubeflow.org/gke-accelerator: Tesla_V100
```

needs to be replaced by `affinity`. 

```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: gpt-pvc
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 2
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - Tesla_V100
```

It's hard to track down when the user gives an invalid label.

`Affinity` requires `serving.kubeflow.org/v1beta1`

## TODO
- [ ] - do require changes in GitBook
